roazhon_sorcers/urls.py
import django
from django.urls import path, include, re_path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('comments/', include('django_comments.urls')),
    path('froala_editor/', include('froala_editor.urls')),
    path('hitcount/', include('hitcount.urls')),
    path('', include("website.urls")),
]

if settings.DEV:
    urlpatterns.append(re_path(r'^media/(.*)$', django.views.static.serve, {'document_root': settings.MEDIA_ROOT}))

website/urls.py
# -*- coding: utf-8 -*-
from django.urls import include, path, re_path
from website.views import ArticleListView, ArticleDetailView, contactView


urlpatterns = [
    path('', ArticleListView.as_view(), name="website-home"),
    re_path(r'^post/(?P<pk>[0-9]+)$', ArticleDetailView.as_view(), name="website-article"),
    path('contact', contactView, name="website-contact"),
]

website/models.py
from datetime import datetime, timedelta

from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from django.urls import reverse
from django.db import models
from django.db.models.signals import post_delete
from django.utils.translation import ugettext_lazy as _
from django_resized import ResizedImageField

from froala_editor.fields import FroalaField
from hitcount.models import HitCountMixin, HitCount
from website.utils import file_cleanup


class ArticleCategory(models.Model):
    title = models.CharField(_('Title'), max_length=255, unique=True)
    slug = models.SlugField(_("slug"),max_length=140, unique=True)
    
    class Meta:
        ordering = ["title"]

    def __str__(self):
        return "%s" % self.title

    def get_absolute_url(self):
        return reverse("website-home")+"?category="+self.slug


class Article(models.Model, HitCountMixin):
    STATUS_DRAFT = 0
    STATUS_FINISHED = 1
    STATUS_HIDDEN = 2
    STATUS_ASK_FOR_REVIEW = 3
    STATUS = [
            (STATUS_DRAFT, _("Draft")),
            (STATUS_FINISHED, _("Finished")),
            (STATUS_ASK_FOR_REVIEW, _("Ask for review")),
            (STATUS_HIDDEN, _("Hidden"))
            ]


    title              = models.CharField(_('Title'), max_length=255)
    creation_date      = models.DateTimeField(_('Creation date'), default=datetime.now())
    publishing_date    = models.DateTimeField(_('Publication date'), default=datetime.now(), help_text= _("This date specify the minimal date require to see the article"))
    status             = models.IntegerField(_("Status"), default=STATUS_DRAFT, help_text=_("The post status. Will apear in the website in Finished state only"), choices=STATUS)
    created_by         = models.ForeignKey(User, on_delete=models.CASCADE)
    image              = ResizedImageField(upload_to='uploads/article',blank=True, size=[1920, 1080], crop=['middle', 'center'], quality=75)
    M2M_category       = models.ManyToManyField(ArticleCategory)
    content            = FroalaField(help_text=_("You can use http://www.strawpoll.me/ to create polls"))

    hit_count_generic  = GenericRelation(HitCount, object_id_field='object_pk', related_query_name='hit_count_generic_relation')

    class Meta:
        ordering = ["-publishing_date"]

    def __str__(self):
        return "%s" % self.title

    def get_absolute_url(self):
        return reverse("website-article", kwargs={"pk": self.pk})

    @staticmethod
    def get_queryset(category=None):
        now = datetime.now()
        queryset = Article.objects.filter(status=Article.STATUS_FINISHED, publishing_date__lte=now)
        if category:
            queryset = queryset.filter(M2M_category__slug=category)
        return queryset
post_delete.connect(file_cleanup, sender=Article, dispatch_uid="Article.file_cleanup")


class Event(models.Model):
    title = models.CharField(_('Title'), max_length=255)

    time = models.TimeField(_('Time'))
    date = models.DateField(_('Date'), blank=True, null=True, help_text=_("Use this field or frequency, but not both"))
    frequency = models.CharField(_('frequence'), max_length=255, blank=True, help_text=_("Use thi field or date but not both"))

    place   = models.CharField(_('Place'), max_length=255, blank=True)
    image   = ResizedImageField(upload_to='uploads/event', blank=False, size=[350, 300], quality=75)
    url     = models.URLField("url", blank=True, null=True)
    content = FroalaField(blank=True)

    class Meta:
        ordering = ["date", "time", "title"]

    def __str__(self):
        return "%s" % self.title

    @staticmethod
    def get_next_events(limit=4, day_limit=7):
        return Event.objects.filter(date=None) | Event.objects.filter(date__gte= datetime.now() - timedelta(days=day_limit))[:limit]

website/forms.py
# -*- coding: utf-8 -*-

from django.utils.translation import ugettext_lazy as _
from django.forms import ModelForm
from django import forms

class ContactForm (forms.Form):
    subject = forms.CharField(label=_('Sujet'), max_length =100)
    email_from = forms.EmailField(label=_('Mail'), max_length=250)
    message = forms.CharField(label=_('Message'), widget=forms.Textarea)
    cc_myself = forms.BooleanField(required=False)
    honeypot = forms.CharField(label=_('honeypot'), max_length=250, widget=forms.HiddenInput, required=False)

website/views.py
from datetime import datetime

from django.shortcuts import render
from django.template.context import RequestContext
from django.views.generic import TemplateView, DetailView, ListView
from django.core.mail import send_mail
from django.contrib.auth.models import User

from website.models import ArticleCategory, Article, Event
from website.forms import ContactForm

class ArticleListView(ListView):
    template_name = "website/home.html"
    model = Article
    paginate_by = 5

    def get_queryset(self):
        category = self.request.GET.get("category", None)
        return self.model.get_queryset(category)


class ArticleDetailView(DetailView):
    template_name = "website/article.html"
    model = Article

    #def get_context_data(self, **kwargs):
    #    context = super(ArticleDetailView, self).get_context_data(**kwargs)
    #    return context

    #def get_queryset(self):
    #    now = datetime.now()
    #    queryset = self.model.objects.filter(publishing_date__lte=now)
    #    return queryset

def contactView(request):
    form = None
    sent = False
    if request.method == 'POST':
        form = ContactForm (request.POST)

        if form.is_valid():
            honeypot = form.cleaned_data['honeypot']
            if not honeypot:
                subject = "[Roazhon Sorcers website] " + form.cleaned_data['subject']
                email_from = form.cleaned_data['email_from']
                message = form.cleaned_data['message']
                cc_myself = form.cleaned_data['cc_myself']

                email_to = [User.objects.get(username="admin").email,]

                if cc_myself :
                    email_to.append(email_from)

                send_mail(subject, message, email_from, email_to, fail_silently=False)

            form = ContactForm()
            sent = True

    else:
        form = ContactForm()


    return render(request, "website/contact.html", {
            "form" : form,
            "sent" : sent,
        }, content_type='text/html')

website/templates/base.html
{% load website_tags generic_flatblocks mkrange hitcount_tags humanize %}
{% spaceless %}
<!DOCTYPE html>
<html>
    <head>
        <title>Roazhon Sorcers{% block app.title %}{% endblock %}</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{{STATIC_URL}}website/css/website.css?{% now "Ymd-hi" %}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        {% block app.headstyles %}{% endblock %}
        {% block app.headscripts %}{% endblock %}
        {% block app.headextra %} {% endblock %}

        {% block document.favicon %}
            <link rel="icon" type="image/png" href="{{STATIC_URL}}website/img/icon.png" />
        {% endblock%}
    </head>

    <body>
        {% GetArticleCategories as article_categories %}
        <!-- Navbar -->
        <div class="w3-bar w3-theme w3-left-align">
            <div class="w3-content">
                <!-- for small screens -->
                <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-hover-white w3-theme" href="javascript:void(0);" onclick="openNav()"><i class="fa fa-bars"></i></a>
                <!-- for all screens -->
                <a href="{% url "website-home" %}" class="w3-bar-item w3-button w3-hover-white">
                    <i class="fa fa-home w3-margin-right"></i>Accueil
                </a>
                <!-- for non small screens -->
                <div class="w3-dropdown-hover w3-hide-small">
                    <button class="w3-button" title="Notifications">Articles <i class="fa fa-caret-down"></i></button>
                    <div class="w3-dropdown-content w3-card-4 w3-bar-block">
                        {% for object in article_categories %}
                        <a href="{{object.get_absolute_url}}" class="w3-bar-item w3-button">{{object|title}}</a>
                        {% endfor %}
                    </div>
                </div>
                <a href="{% url "website-contact" %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Contact</a>
            </div>
        </div>
        <!-- Navbar on small screens show with JS -->
        <div id="navDemo" class="w3-bar-block w3-theme-d2 w3-hide w3-hide-large w3-hide-medium">
            <div class="w3-dropdown-hover w3-bar-item">
                <button class="w3-button" title="Notifications">Articles <i class="fa fa-caret-down"></i></button>
                <div class="w3-dropdown-content w3-card-4 w3-bar-block">
                    {% for object in article_categories %}
                    <a href="{{object.get_absolute_url}}" class="w3-bar-item w3-button">{{object|title}}</a>
                    {% endfor %}
                </div>
            </div>
            <a href="{% url "website-contact" %}" class="w3-bar-item w3-button">Contact</a>
        </div>

        <div id="body-wrapper">
            <!-- Header -->
            {% gblock "home-image" for "gblocks.TitleTextAndImage" into "home_image" %}
            <header>
            {% block app.header %}
                <h1>{{home_image.title}}</h1>
            {% endblock %}
            </header>

            <!-- Grid -->
            <div id="content">
                <!-- entries -->
                <div id="content-main">
                    {% block app.content %}{% endblock %}
                </div>

                <div id="content-side">
                    <!-- About -->
                    <div id="about">
                        <img src="{{home_image.image.url}}">
                        <div class="w3-container w3-white">
                            <p>{{home_image.text}}</p>
                            {% if home_image_admin_url %}
                                <p><a href="{{ home_image_admin_url }}">edit</a></p>
                            {% endif %}
                        </div>
                    </div>
                    <!-- Posts -->
                    <div class="side-block">
                        <div><h4>Articles Populaires</h4></div>
                        <ul class="w3-hoverable">
                            {% GetPopularArticles as popular_posts %}
                            {% for object in popular_posts %}
                            <li onclick="window.location.href='{{object.get_absolute_url}}'" class="link">
                                <img src="{{object.image.url}}" alt="{{object}}">
                                <span class="w3-large">{{object}}</span>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% comment %}
                    <!-- Labels / tags -->
                    <div class="side-block">
                        <div><h4>Catégories</h4></div>
                        <div class="w3-white">
                            <p>
                            {% for object in article_categories %}
                                <a href="{{object.get_absolute_url}}" class="tag">{{object|title}}</a>
                            {% endfor %}
                            </p>
                        </div>
                    </div>
                    {% endcomment %}


                    <div class="side-block">
                        <div><h4>Évènements</h4></div>
                        <ul>
                            {% GetEvents as event_list %}
                            {% for object in event_list %}
                            <li>
                                {% if object.image %}
                                <img src="{{object.image.url}}" alt="{{object}}">
                                {% endif %}
                                <span class="w3-large">{{object}}</span>
                                {% if object.place %}<p>{{object.place}}</p>{% endif %}
                                <p>{% if object.date %}Le {{object.date|naturalday}}&nbsp;{% endif %}
                                    {% if object.frequency %}{{object.frequency}}&nbsp;{% endif %}
                                    à {{object.time|time:"H\hi"}}
                                </p>
                                {% if object.content%}<p>{{object.content|safe}}</p>{% endif %}
                                {% if object.url %}<a href="{{object.url}}" target="_blank">Plus d'info</a>{% endif %}
                            </li>
                        {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <!-- Footer -->
        <footer>
            <div>
                {% comment %}
                <div class="sponsor">
                    <p>Équipe sponsorisée par Ultimate Guard. Retrouvez tous leurs produits sur leur site</p>
                    <a href="http://www.ultimateguard.com/" target="_blank"><img src="{{STATIC_URL}}/website/img/UltimateGuard.png"/></a>
                </div>
                {% endcomment %}
                <div class="juridic">
                    {% gblock "home-juridic" for "gblocks.Text" into "block" %}
                    <p>{{block.text|safe}}</p>
                    {% if block_admin_url %}<p><a href="{{ block_admin_url }}">edit</a></p>{% endif %}
                </div>
                <div class="logo">
                    <p>Retrouvez nous également sur les réseaux sociaux</p>
                    <a class="fa fa-facebook-official" target="_blank" href="https://www.facebook.com/roazhon.sorcers/"></a>
                    <a class="fa fa-twitter" target="_blank" href="https://twitter.com/RoazhonSorcers"></a>
                    <a class="fa fa-instagram" target="_blank" href="https://www.instagram.com/roazhonsorcersofficiel/"></a>
                    <a class="fa fa-youtube" target="_blank" href="https://www.youtube.com/channel/UC0fPJXfIaf1scqGkNi5PE2g"></a>
                    {% comment %}
                    <i class="fa fa-snapchat w3-hover-opacity"></i>
                    <i class="fa fa-pinterest-p w3-hover-opacity"></i>
                    <i class="fa fa-linkedin w3-hover-opacity"></i>
                    {% endcomment %}
                </div>
            </div>
        </footer>

        <script>
            // Accordion
            function myFunction(id) {
                var x = document.getElementById(id);
                if (x.className.indexOf("w3-show") == -1) {
                    x.className += " w3-show";
                    x.previousElementSibling.className += " w3-theme-d1";
                } else {
                    x.className = x.className.replace("w3-show", "");
                    x.previousElementSibling.className =
                        x.previousElementSibling.className.replace(" w3-theme-d1", "");
                }
            }

            // Used to toggle the menu on smaller screens when clicking on the menu button
            function openNav() {
                var x = document.getElementById("navDemo");
                if (x.className.indexOf("w3-show") == -1) {
                    x.className += " w3-show";
                } else {
                    x.className = x.className.replace(" w3-show", "");
                }
            }
        </script>

        {% block app.scripts %}{% endblock %}

    </body>
</html>
{% endspaceless %}